name = "lasada"
version = "0.1.0"
defaultTargets = ["Lasada", "test_lasada"]

[[require]]
name = "lyceum"
path = "../Lyceum"

[[lean_lib]]
name = "Lasada"

[[lean_exe]]
name = "test_lasada"
srcDir = "tests"
root = "TestLasada"

[[lean_exe]]
name = "evaluate_models"
root = "Evaluate"


